apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: nginx-test
    app.kubernetes.io/component: nginx-test
    app: nginx-test
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: nginx-test
      app.kubernetes.io/component: nginx-test
      app: nginx-test
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
